// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./components/ThemeProvider";
import Header from "./components/common/Header";
import LayoutClient from "./components/sections/LayoutClient";
import Providers from "./providers";
import { AudioPlayerProvider } from "./providers/AudioPlayerProvider";

// 👇 추가
import RouteLoader from "./components/common/RouteLoader";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko" suppressHydrationWarning>
    <body className="...">
      <RouteLoader />
      <Providers>
        <ThemeProvider>
          <Header />
          <AudioPlayerProvider>
            {children}
            <LayoutClient /> {/* 여기서는 modal-root 제거! */}
            {/* <RouteLoader /> ← 이건 중복이니 삭제 권장 */}
          </AudioPlayerProvider>
        </ThemeProvider>
      </Providers>
      <div id="modal-root" />
    </body>
  </html>
);
}